-- Context:
-- Smart Food Delivery Management System (ISTE-436)
--
-- Concurrency focus:
-- - Stock changes on MENU_ITEM must be safe under concurrent ordering (lost update prevention).
-- - Driver assignment must serialize on the DRIVER row.

SET DEFINE OFF

PROMPT Dropping existing tables (ignore errors if first install)...

BEGIN
  EXECUTE IMMEDIATE 'DROP TABLE order_status_log';
EXCEPTION WHEN OTHERS THEN NULL; END;
/

BEGIN
  EXECUTE IMMEDIATE 'DROP TABLE review';
EXCEPTION WHEN OTHERS THEN NULL; END;
/

BEGIN
  EXECUTE IMMEDIATE 'DROP TABLE payment';
EXCEPTION WHEN OTHERS THEN NULL; END;
/

BEGIN
  EXECUTE IMMEDIATE 'DROP TABLE delivery';
EXCEPTION WHEN OTHERS THEN NULL; END;
/

BEGIN
  EXECUTE IMMEDIATE 'DROP TABLE order_item';
EXCEPTION WHEN OTHERS THEN NULL; END;
/

BEGIN
  EXECUTE IMMEDIATE 'DROP TABLE orders';
EXCEPTION WHEN OTHERS THEN NULL; END;
/

BEGIN
  EXECUTE IMMEDIATE 'DROP TABLE menu_item';
EXCEPTION WHEN OTHERS THEN NULL; END;
/

BEGIN
  EXECUTE IMMEDIATE 'DROP TABLE restaurant';
EXCEPTION WHEN OTHERS THEN NULL; END;
/

BEGIN
  EXECUTE IMMEDIATE 'DROP TABLE driver';
EXCEPTION WHEN OTHERS THEN NULL; END;
/

BEGIN
  EXECUTE IMMEDIATE 'DROP TABLE customer';
EXCEPTION WHEN OTHERS THEN NULL; END;
/

PROMPT Creating tables...

CREATE TABLE customer (
  customer_id  NUMBER GENERATED BY DEFAULT ON NULL AS IDENTITY,
  name         VARCHAR2(20) NOT NULL,
  phone        VARCHAR2(15) NOT NULL,
  address      VARCHAR2(255),
  created_at   DATE DEFAULT SYSDATE NOT NULL,
  status       CHAR(1) DEFAULT 'A' NOT NULL,
  CONSTRAINT pk_customer PRIMARY KEY (customer_id)
) TABLESPACE DATA_2;

CREATE TABLE restaurant (
  restaurant_id NUMBER GENERATED BY DEFAULT ON NULL AS IDENTITY,
  name          VARCHAR2(20) NOT NULL,
  cuisine_type  VARCHAR2(20) NOT NULL,
  opening_time  DATE,
  closing_time  DATE,
  status        CHAR(1) DEFAULT 'A' NOT NULL,
  CONSTRAINT pk_restaurant PRIMARY KEY (restaurant_id)
) TABLESPACE DATA_2;

CREATE TABLE menu_item (
  item_id       NUMBER GENERATED BY DEFAULT ON NULL AS IDENTITY,
  restaurant_id NUMBER NOT NULL,
  name          VARCHAR2(20) NOT NULL,
  price         NUMBER(8,2) NOT NULL,
  category      VARCHAR2(20) NOT NULL,
  is_available  CHAR(1) DEFAULT 'Y' NOT NULL,
  stock_qty     NUMBER DEFAULT 0 NOT NULL,
  CONSTRAINT pk_menu_item PRIMARY KEY (item_id)
) TABLESPACE DATA_2;

CREATE TABLE orders (
  order_id       NUMBER GENERATED BY DEFAULT ON NULL AS IDENTITY,
  customer_id    NUMBER NOT NULL,
  restaurant_id  NUMBER NOT NULL,
  order_time     DATE DEFAULT SYSDATE NOT NULL,
  status         VARCHAR2(20) NOT NULL,
  total_amount   NUMBER(10,2) NOT NULL,
  CONSTRAINT pk_orders PRIMARY KEY (order_id)
) TABLESPACE DATA;

CREATE TABLE order_item (
  order_id    NUMBER NOT NULL,
  item_id     NUMBER NOT NULL,
  quantity    NUMBER NOT NULL,
  unit_price  NUMBER(8,2) NOT NULL,
  subtotal    NUMBER(10,2) NOT NULL,
  CONSTRAINT pk_order_item PRIMARY KEY (order_id, item_id)
) TABLESPACE DATA;

CREATE TABLE driver (
  driver_id         NUMBER GENERATED BY DEFAULT ON NULL AS IDENTITY,
  name              VARCHAR2(20) NOT NULL,
  status            CHAR(1) DEFAULT 'A' NOT NULL,
  total_deliveries  NUMBER DEFAULT 0 NOT NULL,
  avg_rating        NUMBER(3,2),
  CONSTRAINT pk_driver PRIMARY KEY (driver_id)
) TABLESPACE DATA_2;

CREATE TABLE delivery (
  delivery_id      NUMBER GENERATED BY DEFAULT ON NULL AS IDENTITY,
  order_id         NUMBER NOT NULL,
  driver_id        NUMBER NOT NULL,
  pickup_time      DATE,
  delivery_time    DATE,
  delivery_status  VARCHAR2(20) NOT NULL,
  CONSTRAINT pk_delivery PRIMARY KEY (delivery_id)
) TABLESPACE DATA;

CREATE TABLE payment (
  payment_id     NUMBER GENERATED BY DEFAULT ON NULL AS IDENTITY,
  order_id       NUMBER NOT NULL,
  amount         NUMBER(10,2) NOT NULL,
  method         VARCHAR2(20) NOT NULL,
  status         CHAR(1) DEFAULT 'N' NOT NULL,
  payment_time   DATE,
  CONSTRAINT pk_payment PRIMARY KEY (payment_id)
) TABLESPACE DATA;

CREATE TABLE review (
  review_id  NUMBER GENERATED BY DEFAULT ON NULL AS IDENTITY,
  order_id   NUMBER NOT NULL,
  rating     NUMBER NOT NULL,
  comment    VARCHAR2(255),
  CONSTRAINT pk_review PRIMARY KEY (review_id)
) TABLESPACE DATA_2;

CREATE TABLE order_status_log (
  log_id      NUMBER GENERATED BY DEFAULT ON NULL AS IDENTITY,
  order_id    NUMBER NOT NULL,
  old_status  VARCHAR2(20),
  new_status  VARCHAR2(20) NOT NULL,
  change_time DATE DEFAULT SYSDATE NOT NULL,
  CONSTRAINT pk_order_status_log PRIMARY KEY (log_id)
) TABLESPACE DATA;
