OPTIONS (SKIP=1)
LOAD DATA
INFILE 'order_item.csv'
APPEND
INTO TABLE order_item
FIELDS TERMINATED BY ',' OPTIONALLY ENCLOSED BY '"'
TRAILING NULLCOLS
(
  order_id     INTEGER EXTERNAL,
  item_id      INTEGER EXTERNAL,
  quantity     INTEGER EXTERNAL,
  unit_price   DECIMAL EXTERNAL,
  subtotal     "TO_NUMBER(REPLACE(REPLACE(:subtotal, CHR(13), ''), CHR(10), ''))"
)
